### PR TITLE
added basic models and enums

### PR DESCRIPTION
**Pull request by BeeMoe5**
ignore client.py i forgot to exclude it when pushing

### CODE REVIEW

**Review by Skelmis — CHANGES_REQUESTED** [review]
I'd remove the request specific layouts as they can be denoted as arguments to the method themselves. It's just one less step end users need to worry about.

N.b. responses would be dataclass's so they should stay, it's just the request objects.

Otherwise lgtm

**Review by Skelmis — APPROVED** [review]

**Comment by rf20008** [comment]
You should probably document the things that were added (as there is no documentation yet) but otherwise it's okay

**Comment by BeeMoe5** [comment]
> You should probably document the things that were added (as there is no documentation yet) but otherwise it's okay

Yea, I'll do that unless someone else wants to

**Review by rf20008 — APPROVED** [review]
Testing this, this is okay. We should do the documentation soon (but that shouldn't impede this PR.)

**Pull request merged**
